function S_m2ZD(fbWNJgg) {
    switch (fbWNJgg) {
      case "gHQBmnA":
        return E_eCa8P.getStyles;
      case "Darbeu":
        return E_eCa8P.Array;
      case "vwqGHhA":
        return E_eCa8P.window;
      case "u8Ef0G":
        return E_eCa8P.o7z5GYq;
      case "qzjqsc":
        return E_eCa8P.TMfXZL;
      case "QpKAip":
        return E_eCa8P.setTimeout;
      case "R7ZtTW":
        return E_eCa8P.DataView;
      case "UCtEN2":
        return E_eCa8P.DisplayName;
      case "2YzG8Ia":
        return E_eCa8P.a8DrRf;
      case "gXfqnaK":
        return E_eCa8P.ErrorBoundary;
      case "axItOek":
        return E_eCa8P.WBS7aCB;
      case "f0uwKQ":
        return E_eCa8P.isAttached;
      case "Eg9NFoR":
        return E_eCa8P.String;
      case "Lt_Oxh":
        return E_eCa8P.Set;
      case "Pfhk8wH":
        return E_eCa8P.Error;
      case "fBgIbFF":
        return E_eCa8P.Z1sl5nb;
      case "2QxV4dg":
        return E_eCa8P.HmuusN;
      case "jb6jMF":
        return E_eCa8P.YWJxH3;
      case "qw3aUMF":
        return E_eCa8P.ZePWM_z;
      case "8quXxsf":
        return E_eCa8P.UtPTiT;
      case "CbU0Uv":
        return E_eCa8P.ArrayBuffer;
      case "f2A3rS":
        return E_eCa8P.Math;
      case "BQkLLyu":
        return E_eCa8P.console;
      case "Xp3AYyy":
        return E_eCa8P.DGMOadj;
      case "Drp3Ln":
        return E_eCa8P.qXa1SnT;
      case "GlTxr3":
        return E_eCa8P.Object;
      case "Mxf3Ei":
        return E_eCa8P.Uint8Array;
      case "tXPb3QP":
        return E_eCa8P.buildCharMap;
      case "Bb9yW5W":
        return E_eCa8P.redacted;
      case "8ZEFua":
        return E_eCa8P.m6CvjV;
      case "A6vv3kA":
        return E_eCa8P.bmWmqz;
      case "qcIfAE":
        return E_eCa8P.process;
      case "KEVoyR":
        return E_eCa8P.ZpNGAy;
      case "cPq49J":
        return E_eCa8P.R8Irg8;
      case "wJYc2XO":
        return E_eCa8P.decodeURIComponent;
      case "owbhGE":
        return E_eCa8P.btoa;
      case "CH7L0Cd":
        return E_eCa8P.KRzgyF;
      case "ZnAu8wc":
        return E_eCa8P.document;
      case "ggwzBFA":
        return E_eCa8P.TextEncoder;
      case "fcQocHX":
        return E_eCa8P.rS8lad;
      case "uraNFi":
        return E_eCa8P.vaSfRSF;
      case "rJUHqpi":
        return E_eCa8P.clearInterval;
      case "bPfssFL":
        return E_eCa8P.LQGrvtb;
      case "ZBUOW1":
        return E_eCa8P.uvzb9v;
      case "uoXXkFE":
        return E_eCa8P.hrBkmul;
      case "xo1j5U4":
        return E_eCa8P.ykbD2u;
      case "VgYH_e":
        return E_eCa8P.Function;
      case "b7oD_d":
        return E_eCa8P.setInterval;
      case "uzKXWst":
        return E_eCa8P.wFaUnM;
      case "aH7GkGg":
        return E_eCa8P.MnnLWU;
      case "JaFGEfw":
        return E_eCa8P.Number;
    }
  }
  S_m2ZD("vwqGHhA");